// WATCHOUT 7 User Guide - Content Data
// End-user focused documentation

const wikiContent = {
  "1. Getting Started": {
    "overview": "<h1>GETTING STARTED</h1>\n\n<p>Welcome to <strong>WATCHOUT 7</strong> – the premier multi-display presentation and production system from Dataton. This guide will help you create stunning visual experiences using projectors, LED walls, monitors, and other display technologies.</p>",
    "sections": {
      "Welcome to WATCHOUT 7": "<h2>Welcome to WATCHOUT 7</h2>\n\n<p>WATCHOUT 7 is a powerful software system for creating and presenting multi-display shows. Whether you're working with a single projector or dozens of displays, WATCHOUT gives you complete control over your visual content.</p>\n\n<h3>What You Can Create</h3>\n<ul>\n<li>Multi-screen video presentations</li>\n<li>Immersive projection mapping experiences</li>\n<li>Seamless video walls</li>\n<li>Interactive installations</li>\n<li>Live event visuals with audio synchronization</li>\n</ul>\n\n<h3>Key Features</h3>\n<ul>\n<li><strong>Timeline-Based Editing</strong> – Precisely control when and how media appears</li>\n<li><strong>Multi-Display Support</strong> – Drive unlimited displays from a single show</li>\n<li><strong>Real-time Preview</strong> – See your changes instantly</li>\n<li><strong>Network Operation</strong> – Control remote display computers seamlessly</li>\n<li><strong>Professional Video Codecs</strong> – Support for HAP, ProRes, HEVC, and more</li>\n</ul>",
      "System Requirements": "<h2>System Requirements</h2>\n\n<h3>Producer Computer (Editing)</h3>\n<table>\n<tr><th>Component</th><th>Minimum</th><th>Recommended</th></tr>\n<tr><td>Operating System</td><td>Windows 10 (64-bit)</td><td>Windows 11 (64-bit)</td></tr>\n<tr><td>Processor</td><td>Intel Core i5 or AMD equivalent</td><td>Intel Core i7/i9 or AMD Ryzen 7/9</td></tr>\n<tr><td>RAM</td><td>8 GB</td><td>32 GB or more</td></tr>\n<tr><td>Graphics</td><td>DirectX 12 compatible GPU</td><td>NVIDIA RTX series or AMD equivalent</td></tr>\n<tr><td>Storage</td><td>SSD with 50 GB free</td><td>NVMe SSD with 500 GB+ free</td></tr>\n<tr><td>Network</td><td>Gigabit Ethernet</td><td>10 Gigabit Ethernet</td></tr>\n</table>\n\n<h3>Display Computer (Playback)</h3>\n<table>\n<tr><th>Component</th><th>Requirement</th></tr>\n<tr><td>Operating System</td><td>Windows 10/11 (64-bit)</td></tr>\n<tr><td>Graphics</td><td>NVIDIA professional GPU (Quadro/RTX) recommended</td></tr>\n<tr><td>Storage</td><td>Fast SSD for media playback</td></tr>\n<tr><td>Network</td><td>Gigabit Ethernet (same subnet as Producer)</td></tr>\n</table>",
      "Installing WATCHOUT": "<h2>Installing WATCHOUT</h2>\n\n<h3>Download and Installation</h3>\n<ol>\n<li>Download the WATCHOUT 7 installer from <strong>dataton.com</strong></li>\n<li>Run the installer as Administrator</li>\n<li>Follow the on-screen instructions</li>\n<li>Restart your computer when prompted</li>\n</ol>\n\n<h3>License Activation</h3>\n<p>WATCHOUT requires a valid license to operate. You can activate your license in the License window accessible from the Help menu.</p>\n\n<h3>Firewall Configuration</h3>\n<p>During installation, WATCHOUT automatically configures Windows Firewall rules. If you use third-party firewall software, ensure these ports are open:</p>\n<ul>\n<li><strong>TCP 3039</strong> – Primary communication</li>\n<li><strong>TCP 3040</strong> – Asset transfer</li>\n<li><strong>UDP 40400-40500</strong> – Discovery and sync</li>\n</ul>",
      "Launching the Application": "<h2>Launching the Application</h2>\n\n<p>After installation, launch WATCHOUT from the Start menu or desktop shortcut.</p>\n\n<h3>First Launch</h3>\n<p>On first launch, you'll see the <strong>Welcome screen</strong> with options to:</p>\n<ul>\n<li><strong>Create New Show</strong> – Start a fresh project</li>\n<li><strong>Open Recent</strong> – Access recently edited shows</li>\n<li><strong>Open Show</strong> – Browse for an existing .watch file</li>\n</ul>\n\n<h3>The Main Interface</h3>\n<p>The WATCHOUT interface consists of several key windows:</p>\n<ul>\n<li><strong>Stage</strong> – Visual preview of your displays and content</li>\n<li><strong>Timeline</strong> – Where you arrange and time your media</li>\n<li><strong>Assets</strong> – Your media library</li>\n<li><strong>Properties</strong> – Settings for selected items</li>\n<li><strong>Network</strong> – Connected display servers</li>\n</ul>",
      "Quick Start Tutorial": "<h2>Quick Start Tutorial</h2>\n\n<p>Follow these steps to create your first show:</p>\n\n<h3>Step 1: Create a New Show</h3>\n<p>Go to <strong>File → New</strong> or press <code>Ctrl+N</code>.</p>\n\n<h3>Step 2: Add a Display</h3>\n<p>Go to <strong>Stage → Add Display</strong>. This creates a display area representing your output device.</p>\n\n<h3>Step 3: Import Media</h3>\n<p>Drag image or video files directly into the <strong>Assets</strong> window, or use <strong>Media → Add Media File</strong>.</p>\n\n<h3>Step 4: Add Media to Timeline</h3>\n<p>Drag your media from the Assets window onto the Timeline. Position it on a layer at the desired time.</p>\n\n<h3>Step 5: Position on Stage</h3>\n<p>With the cue selected, drag it on the Stage window to position it on your display.</p>\n\n<h3>Step 6: Preview</h3>\n<p>Press <strong>Spacebar</strong> to play your timeline and preview the result.</p>\n\n<h3>Step 7: Save</h3>\n<p>Go to <strong>File → Save</strong> or press <code>Ctrl+S</code> to save your show.</p>"
    }
  },
  "2. The Interface": {
    "overview": "<h1>THE INTERFACE</h1>\n\n<p>WATCHOUT 7 features a modern, flexible interface designed for efficient show production. Learn how to navigate and customize your workspace for maximum productivity.</p>",
    "sections": {
      "Main Window Overview": "<h2>Main Window Overview</h2>\n\n<p>The WATCHOUT interface is divided into several dockable windows that can be arranged to suit your workflow.</p>\n\n<h3>Menu Bar</h3>\n<p>The menu bar at the top provides access to all commands organized in logical groups: File, Edit, Stage, Media, Timeline, Tween, Window, and Help.</p>\n\n<h3>Toolbar</h3>\n<p>Quick access buttons for common operations like play, pause, and zoom controls.</p>\n\n<h3>Window Areas</h3>\n<p>The main workspace is divided into panels that can be rearranged, resized, or floated as separate windows.</p>",
      "The Stage Window": "<h2>The Stage Window</h2>\n\n<p>The Stage is your visual canvas – a representation of all your displays and how content appears on them.</p>\n\n<h3>Navigation</h3>\n<ul>\n<li><strong>Pan</strong> – Hold <code>Ctrl+Alt</code> and drag</li>\n<li><strong>Zoom</strong> – Use <code>Ctrl+Mouse Wheel</code> or zoom buttons</li>\n<li><strong>Frame All</strong> – Press <code>Ctrl+Shift+D</code> to fit all displays in view</li>\n</ul>\n\n<h3>View Modes</h3>\n<ul>\n<li><strong>Default</strong> – Standard 2D editing view</li>\n<li><strong>Perspective</strong> – 3D view for mapping projects</li>\n<li><strong>Projector View</strong> – See content from projector's perspective</li>\n</ul>\n\n<h3>Working with Content</h3>\n<p>Select, move, and transform media cues directly on the Stage. Use handles to resize and rotate.</p>",
      "The Timeline Window": "<h2>The Timeline Window</h2>\n\n<p>The Timeline is where you orchestrate your show – arranging media and controlling precisely when things happen.</p>\n\n<h3>Timeline Structure</h3>\n<ul>\n<li><strong>Timecode Ruler</strong> – Shows time in hours:minutes:seconds:frames</li>\n<li><strong>Layers</strong> – Horizontal tracks for organizing content (higher layers appear on top)</li>\n<li><strong>Play Cursor</strong> – The red vertical line indicating current playback position</li>\n</ul>\n\n<h3>Basic Operations</h3>\n<ul>\n<li><strong>Play/Pause</strong> – Press <code>Spacebar</code></li>\n<li><strong>Jump to Time</strong> – Click in the timecode ruler</li>\n<li><strong>Zoom</strong> – Use <code>Numpad +/-</code> or zoom controls</li>\n<li><strong>Add Layer</strong> – Press <code>Ctrl+I</code></li>\n</ul>",
      "The Assets Window": "<h2>The Assets Window</h2>\n\n<p>The Assets window is your media library – all images, videos, and audio files available for use in your show.</p>\n\n<h3>Adding Media</h3>\n<ul>\n<li>Drag files directly into the window</li>\n<li>Use <strong>Media → Add Media File</strong></li>\n<li>Right-click and select <strong>Add Media</strong></li>\n</ul>\n\n<h3>Organization</h3>\n<p>Create folders to organize your assets. Right-click and select <strong>Add Folder</strong>.</p>\n\n<h3>Asset Information</h3>\n<p>Select an asset to see its properties: resolution, duration, file path, and codec information.</p>",
      "The Properties Panel": "<h2>The Properties Panel</h2>\n\n<p>The Properties panel shows settings for whatever is currently selected – displays, cues, or media.</p>\n\n<h3>Accessing Properties</h3>\n<ul>\n<li>Select an item and view its properties automatically</li>\n<li>Double-click an item to open detailed settings</li>\n<li>Press <code>Enter</code> with an item selected</li>\n</ul>\n\n<h3>Common Properties</h3>\n<ul>\n<li><strong>Position</strong> – X, Y coordinates on stage</li>\n<li><strong>Scale</strong> – Size as percentage</li>\n<li><strong>Rotation</strong> – Rotation in degrees</li>\n<li><strong>Opacity</strong> – Transparency level</li>\n</ul>",
      "The Network Window": "<h2>The Network Window</h2>\n\n<p>The Network window shows all WATCHOUT devices on your network and their status.</p>\n\n<h3>Device Status</h3>\n<ul>\n<li><strong>Green</strong> – Online and ready</li>\n<li><strong>Yellow</strong> – Busy or loading</li>\n<li><strong>Red</strong> – Offline or error</li>\n</ul>\n\n<h3>Connecting Devices</h3>\n<p>WATCHOUT automatically discovers devices on the same network. Click a device to view its details and assign displays.</p>",
      "Customizing Your Workspace": "<h2>Customizing Your Workspace</h2>\n\n<p>WATCHOUT's interface is fully customizable to match your workflow.</p>\n\n<h3>Rearranging Windows</h3>\n<p>Drag window title bars to dock them in new locations or float them as separate windows.</p>\n\n<h3>Saving Layouts</h3>\n<p>Go to <strong>Window → Save Layout</strong> to save your current arrangement. Load saved layouts from the same menu.</p>\n\n<h3>Layout Presets</h3>\n<p>Use <code>Ctrl+Shift+1</code> through <code>Ctrl+Shift+9</code> to save quick-access layout presets.</p>\n\n<h3>Theme</h3>\n<p>Toggle between dark and light themes from the Window menu.</p>"
    }
  },
  "3. Working with Shows": {
    "overview": "<h1>WORKING WITH SHOWS</h1>\n\n<p>A WATCHOUT show (.watch file) contains all your display configurations, media references, timeline data, and settings. Learn how to create, manage, and organize your shows effectively.</p>",
    "sections": {
      "Creating a New Show": "<h2>Creating a New Show</h2>\n\n<p>Start a new project from scratch:</p>\n<ol>\n<li>Go to <strong>File → New</strong> or press <code>Ctrl+N</code></li>\n<li>If you have unsaved changes, you'll be prompted to save first</li>\n<li>A blank show opens with default settings</li>\n</ol>\n\n<h3>Show File Location</h3>\n<p>Choose a location for your show file that's accessible from all computers in your setup. Consider using a shared network drive for multi-user projects.</p>",
      "Opening Existing Shows": "<h2>Opening Existing Shows</h2>\n\n<h3>Open Methods</h3>\n<ul>\n<li><strong>File → Open</strong> or <code>Ctrl+O</code> – Browse for a show file</li>\n<li><strong>Recent Shows</strong> – Access from File menu</li>\n<li><strong>Double-click</strong> – Open .watch files directly from Windows Explorer</li>\n</ul>\n\n<h3>Connecting to a Director</h3>\n<p>To join an existing show session on the network, use <strong>File → Connect to Director</strong> and select the active show.</p>",
      "Saving Your Work": "<h2>Saving Your Work</h2>\n\n<h3>Save Commands</h3>\n<ul>\n<li><strong>Save</strong> (<code>Ctrl+S</code>) – Save to current location</li>\n<li><strong>Save As</strong> – Save with a new name or location</li>\n<li><strong>Save Copy</strong> – Create a backup without changing current file</li>\n</ul>\n\n<h3>Auto-Recovery</h3>\n<p>WATCHOUT automatically saves recovery data. If the application closes unexpectedly, you'll be prompted to recover your work on next launch.</p>",
      "Show Properties": "<h2>Show Properties</h2>\n\n<p>Access show-wide settings from <strong>File → Properties</strong>.</p>\n\n<h3>Available Settings</h3>\n<ul>\n<li><strong>Frame Rate</strong> – Target playback frame rate (30, 60 fps, etc.)</li>\n<li><strong>Stage Size</strong> – Overall coordinate space dimensions</li>\n<li><strong>Audio Settings</strong> – Default audio output configuration</li>\n</ul>"
    }
  },
  "4. Displays and Outputs": {
    "overview": "<h1>DISPLAYS AND OUTPUTS</h1>\n\n<p>Learn how to configure displays, projectors, and video walls in WATCHOUT. Proper display setup is essential for achieving seamless multi-screen presentations.</p>",
    "sections": {
      "Adding Displays": "<h2>Adding Displays</h2>\n\n<h3>Adding a Standard Display</h3>\n<ol>\n<li>Go to <strong>Stage → Add Display</strong></li>\n<li>A new display appears on the Stage</li>\n<li>Position it to match your physical screen arrangement</li>\n<li>Set the resolution in the Properties panel</li>\n</ol>\n\n<h3>Display Properties</h3>\n<ul>\n<li><strong>Name</strong> – Descriptive label for the display</li>\n<li><strong>Width/Height</strong> – Resolution in pixels</li>\n<li><strong>Position</strong> – X, Y coordinates on stage</li>\n<li><strong>Output</strong> – Which display server output to use</li>\n</ul>",
      "Virtual Displays": "<h2>Virtual Displays</h2>\n\n<p>Virtual displays are canvas areas that can be used for content composition before mapping to physical displays.</p>\n\n<h3>Creating Virtual Displays</h3>\n<p>Go to <strong>Stage → Add Virtual Display</strong>.</p>\n\n<h3>Use Cases</h3>\n<ul>\n<li>Pre-compositing content for projection mapping</li>\n<li>Creating content zones larger than physical outputs</li>\n<li>Organizing complex multi-layer shows</li>\n</ul>",
      "3D Mapping Projectors": "<h2>3D Mapping Projectors</h2>\n\n<p>For projection onto 3D surfaces, use 3D mapping projectors.</p>\n\n<h3>Adding a 3D Projector</h3>\n<p>Go to <strong>Stage → Add 3D Projector</strong>.</p>\n\n<h3>Configuration</h3>\n<ul>\n<li><strong>Position</strong> – Physical location of the projector in 3D space</li>\n<li><strong>Rotation</strong> – Aim direction (pan, tilt, roll)</li>\n<li><strong>Lens</strong> – Throw ratio and lens shift settings</li>\n<li><strong>Resolution</strong> – Native projector resolution</li>\n</ul>",
      "Display Grid Setup": "<h2>Display Grid Setup</h2>\n\n<p>Quickly create multi-display arrangements using the grid tool.</p>\n\n<h3>Creating a Grid</h3>\n<ol>\n<li>Go to <strong>Stage → Create Display Grid</strong></li>\n<li>Specify rows and columns</li>\n<li>Set bezel compensation if needed</li>\n<li>Click OK to generate displays</li>\n</ol>",
      "Display Properties": "<h2>Display Properties</h2>\n\n<h3>Common Settings</h3>\n<table>\n<tr><th>Property</th><th>Description</th></tr>\n<tr><td>Name</td><td>Identifier for the display</td></tr>\n<tr><td>Resolution</td><td>Width × Height in pixels</td></tr>\n<tr><td>Position</td><td>Stage coordinates (X, Y)</td></tr>\n<tr><td>Output Device</td><td>Which GPU output to use</td></tr>\n<tr><td>Assigned Server</td><td>Which display computer renders this display</td></tr>\n</table>",
      "Edge Blending": "<h2>Edge Blending</h2>\n\n<p>Create seamless panoramas by blending overlapping projector edges.</p>\n\n<h3>Setting Up Edge Blending</h3>\n<ol>\n<li>Position displays with slight overlap</li>\n<li>Access display properties</li>\n<li>Configure soft-edge blend curves</li>\n<li>Adjust blend width and gamma</li>\n</ol>",
      "Geometry Correction": "<h2>Geometry Correction</h2>\n\n<p>WATCHOUT provides multiple tools for correcting projection distortion.</p>\n\n<h3>Correction Methods</h3>\n<ul>\n<li><strong>Keystone</strong> – Basic corner adjustment</li>\n<li><strong>Bezier Warp</strong> – Smooth curve-based correction</li>\n<li><strong>Mesh Warp</strong> – Point-by-point adjustment grid</li>\n</ul>"
    }
  },
  "5. Assets & Asset Manager": {
    "overview": "<h1>ASSETS & ASSET MANAGER</h1>\n\n<p>The Asset Manager is the central hub for all media content in WATCHOUT 7. It handles importing, organizing, optimizing, and distributing media files across your production network. Understanding the Asset Manager is essential for efficient show production.</p>",
    "sections": {
      "Asset Manager": "<h2>Asset Manager</h2>\n\n<p>The Asset Manager is a core component of WATCHOUT 7 that manages all media files used in your shows.</p>\n\n<h3>Overview</h3>\n<p>The Asset Manager runs as a background service and provides:</p>\n<ul>\n<li><strong>Centralized Storage</strong> – All media files are managed from a single location</li>\n<li><strong>Automatic Optimization</strong> – Video files are transcoded to optimal playback formats</li>\n<li><strong>Network Distribution</strong> – Assets are automatically transferred to display servers</li>\n<li><strong>Version Tracking</strong> – Changes to source files are detected and handled</li>\n</ul>\n\n<h3>Assets Window</h3>\n<p>The Assets window displays all media in your show. Access it from <strong>Window → Assets</strong> or press <code>Ctrl+2</code>.</p>\n\n<h3>Adding Assets</h3>\n<ul>\n<li><strong>Drag and Drop</strong> – Drag files directly from Windows Explorer into the Assets window</li>\n<li><strong>Menu</strong> – Use <strong>Media → Add Media File</strong> or <strong>Add Image Sequence</strong></li>\n<li><strong>Right-Click</strong> – Right-click in the Assets window and choose <strong>Add Media</strong></li>\n<li><strong>Asset Watcher</strong> – Automatically import from watched folders</li>\n</ul>\n\n<h3>Asset Organization</h3>\n<p>Organize assets using folders:</p>\n<ol>\n<li>Right-click in the Assets window</li>\n<li>Select <strong>Add Folder</strong></li>\n<li>Drag assets into folders to organize them</li>\n</ol>\n<p>Use <strong>Media → Collapse All Folders</strong> and <strong>Expand All Folders</strong> for quick navigation.</p>",
      "Asset Types": "<h2>Asset Types</h2>\n\n<p>WATCHOUT 7 supports a wide variety of media types, each with specific capabilities and use cases.</p>\n\n<h3>Still Images</h3>\n<table>\n<tr><th>Type</th><th>Formats</th><th>Notes</th></tr>\n<tr><td>Standard Images</td><td>JPEG, PNG, BMP, TGA, TIFF</td><td>Common image formats</td></tr>\n<tr><td>High Dynamic Range</td><td>EXR, HDR</td><td>For HDR displays</td></tr>\n<tr><td>Layered</td><td>PSD</td><td>Imported as flattened image</td></tr>\n<tr><td>Vector</td><td>SVG</td><td>Rasterized at import</td></tr>\n</table>\n\n<h3>Video</h3>\n<table>\n<tr><th>Type</th><th>Formats</th><th>Notes</th></tr>\n<tr><td>GPU-Accelerated</td><td>HAP, HAP Alpha, HAP Q</td><td>Best performance - recommended</td></tr>\n<tr><td>Professional</td><td>ProRes 422/4444, DNxHR</td><td>High quality, decode only</td></tr>\n<tr><td>Compressed</td><td>H.264, HEVC/H.265</td><td>Smaller files, more CPU usage</td></tr>\n<tr><td>Specialty</td><td>NotchLC</td><td>Real-time graphics from Notch</td></tr>\n</table>\n\n<h3>Image Sequences</h3>\n<p>Numbered image files treated as video frames. Supports JPEG, PNG, TGA, TIFF, and EXR sequences.</p>\n\n<h3>Audio</h3>\n<table>\n<tr><th>Format</th><th>Notes</th></tr>\n<tr><td>WAV</td><td>Recommended - uncompressed, best quality</td></tr>\n<tr><td>AIFF</td><td>Uncompressed audio</td></tr>\n<tr><td>MP3</td><td>Compressed audio</td></tr>\n<tr><td>AAC, FLAC, OGG</td><td>Additional compressed formats</td></tr>\n</table>\n\n<h3>Live Sources</h3>\n<ul>\n<li><strong>NDI</strong> – Network Device Interface streams</li>\n<li><strong>Capture Cards</strong> – BlackMagic, AJA, and other capture devices</li>\n<li><strong>Screen Capture</strong> – Capture from desktop or specific windows</li>\n<li><strong>Web Browser</strong> – Render web pages as live content</li>\n</ul>\n\n<h3>Special Types</h3>\n<ul>\n<li><strong>Composition</strong> – Nested timeline as a reusable asset</li>\n<li><strong>Solid Color</strong> – Color fills for backgrounds or overlays</li>\n<li><strong>Dynamic Text</strong> – Text that can be updated at runtime</li>\n</ul>",
      "Asset Properties": "<h2>Asset Properties</h2>\n\n<p>Each asset has properties that control how it behaves in your show. Access properties by selecting an asset and viewing the Properties panel, or double-click to open the Asset Properties dialog.</p>\n\n<h3>General Properties</h3>\n<table>\n<tr><th>Property</th><th>Description</th></tr>\n<tr><td>Name</td><td>Display name in the Assets window</td></tr>\n<tr><td>Source Path</td><td>Location of the original file</td></tr>\n<tr><td>Duration</td><td>Length for video/audio assets</td></tr>\n<tr><td>Dimensions</td><td>Width × Height in pixels</td></tr>\n<tr><td>Frame Rate</td><td>Playback speed for video/sequences</td></tr>\n</table>\n\n<h3>Video Properties</h3>\n<table>\n<tr><th>Property</th><th>Description</th></tr>\n<tr><td>Codec</td><td>Video compression format</td></tr>\n<tr><td>Bit Depth</td><td>Color depth (8-bit, 10-bit, etc.)</td></tr>\n<tr><td>Alpha Channel</td><td>Transparency support</td></tr>\n<tr><td>In Point</td><td>Start trim point</td></tr>\n<tr><td>Out Point</td><td>End trim point</td></tr>\n<tr><td>Loop Mode</td><td>None, Loop, or Ping-Pong</td></tr>\n</table>\n\n<h3>Audio Properties</h3>\n<table>\n<tr><th>Property</th><th>Description</th></tr>\n<tr><td>Sample Rate</td><td>44.1kHz, 48kHz, 96kHz, etc.</td></tr>\n<tr><td>Bit Depth</td><td>16-bit, 24-bit, 32-bit float</td></tr>\n<tr><td>Channels</td><td>Mono, Stereo, 5.1, 7.1, etc.</td></tr>\n<tr><td>Volume</td><td>Default playback level</td></tr>\n</table>\n\n<h3>Optimization Status</h3>\n<ul>\n<li><strong>Pending</strong> (gray) – Not yet optimized</li>\n<li><strong>Optimizing</strong> (yellow) – Currently being processed</li>\n<li><strong>Ready</strong> (green) – Optimized and ready for playback</li>\n<li><strong>Error</strong> (red) – Optimization failed</li>\n<li><strong>Modified</strong> (orange) – Source file has changed, needs re-optimization</li>\n</ul>\n\n<h3>Actions</h3>\n<ul>\n<li><strong>Re-optimize</strong> – Regenerate optimized version</li>\n<li><strong>Reveal in Explorer</strong> – Open source file location</li>\n<li><strong>Find Cues</strong> – Locate all timeline cues using this asset</li>\n<li><strong>Replace Asset</strong> – Swap with a different file</li>\n</ul>",
      "Formats & Codecs": "<h2>Formats & Codecs</h2>\n\n<p>Choosing the right format and codec is crucial for optimal playback performance.</p>\n\n<h3>Recommended Video Codecs</h3>\n<table>\n<tr><th>Codec</th><th>Best For</th><th>Performance</th><th>File Size</th></tr>\n<tr><td><strong>HAP</strong></td><td>Most video content</td><td>★★★★★</td><td>Large</td></tr>\n<tr><td><strong>HAP Alpha</strong></td><td>Video with transparency</td><td>★★★★★</td><td>Very Large</td></tr>\n<tr><td><strong>HAP Q</strong></td><td>Highest quality HAP</td><td>★★★★☆</td><td>Very Large</td></tr>\n<tr><td><strong>ProRes 422</strong></td><td>High quality editing</td><td>★★★☆☆</td><td>Large</td></tr>\n<tr><td><strong>ProRes 4444</strong></td><td>Quality with alpha</td><td>★★★☆☆</td><td>Very Large</td></tr>\n<tr><td><strong>H.264</strong></td><td>Small files, wide compatibility</td><td>★★☆☆☆</td><td>Small</td></tr>\n<tr><td><strong>HEVC/H.265</strong></td><td>Better compression than H.264</td><td>★★☆☆☆</td><td>Very Small</td></tr>\n<tr><td><strong>NotchLC</strong></td><td>Real-time graphics</td><td>★★★★★</td><td>Large</td></tr>\n</table>\n\n<h3>Why HAP is Recommended</h3>\n<ul>\n<li><strong>GPU Decoding</strong> – Decodes directly on the graphics card</li>\n<li><strong>Minimal CPU Usage</strong> – Leaves CPU free for other tasks</li>\n<li><strong>Instant Scrubbing</strong> – Smooth timeline navigation</li>\n<li><strong>High Frame Rates</strong> – Supports 60fps and beyond</li>\n<li><strong>Large Resolutions</strong> – Handles 4K, 8K, and higher</li>\n</ul>\n\n<h3>Container Formats</h3>\n<table>\n<tr><th>Container</th><th>Common Codecs</th></tr>\n<tr><td>.mov</td><td>HAP, ProRes, H.264</td></tr>\n<tr><td>.mp4</td><td>H.264, HEVC</td></tr>\n<tr><td>.avi</td><td>HAP (legacy)</td></tr>\n<tr><td>.mkv</td><td>Various</td></tr>\n</table>\n\n<h3>Audio Codecs</h3>\n<ul>\n<li><strong>PCM/WAV</strong> – Uncompressed, best quality, larger files</li>\n<li><strong>AAC</strong> – High quality compressed</li>\n<li><strong>MP3</strong> – Widely compatible compressed</li>\n</ul>\n\n<h3>Image Formats</h3>\n<table>\n<tr><th>Format</th><th>Transparency</th><th>Best For</th></tr>\n<tr><td>PNG</td><td>Yes (8-bit)</td><td>Graphics, logos, overlays</td></tr>\n<tr><td>JPEG</td><td>No</td><td>Photos, backgrounds</td></tr>\n<tr><td>TIFF</td><td>Yes</td><td>High quality images</td></tr>\n<tr><td>TGA</td><td>Yes</td><td>Legacy graphics</td></tr>\n<tr><td>EXR</td><td>Yes (32-bit)</td><td>HDR content</td></tr>\n</table>",
      "Web User Interface": "<h2>Web User Interface</h2>\n\n<p>WATCHOUT 7 includes a web-based interface for managing assets remotely. This allows team members to upload and organize media without direct access to the production computer.</p>\n\n<h3>Accessing the Web UI</h3>\n<ol>\n<li>Open a web browser on any device on the same network</li>\n<li>Navigate to <code>http://[producer-ip]:3040</code></li>\n<li>The Asset Manager web interface loads automatically</li>\n</ol>\n\n<h3>Features</h3>\n<ul>\n<li><strong>Upload Files</strong> – Drag and drop or browse to upload media</li>\n<li><strong>Browse Assets</strong> – View all assets in the current show</li>\n<li><strong>Create Folders</strong> – Organize assets into folders</li>\n<li><strong>Preview Media</strong> – View thumbnails and preview video</li>\n<li><strong>Check Status</strong> – Monitor optimization progress</li>\n<li><strong>Delete Assets</strong> – Remove unwanted media</li>\n</ul>\n\n<h3>Upload Progress</h3>\n<p>Large files show upload progress in the web interface. Once uploaded, optimization begins automatically.</p>\n\n<h3>Security Considerations</h3>\n<ul>\n<li>The web UI is accessible to anyone on the local network</li>\n<li>Consider network segmentation for production environments</li>\n<li>Use firewall rules to restrict access if needed</li>\n</ul>\n\n<h3>Mobile Access</h3>\n<p>The web interface is responsive and works on tablets and smartphones for on-the-go asset management.</p>",
      "Asset Watcher": "<h2>Asset Watcher</h2>\n\n<p>The Asset Watcher automatically monitors designated folders for new or changed files, streamlining the content workflow.</p>\n\n<h3>Setting Up Watch Folders</h3>\n<ol>\n<li>Go to <strong>Settings → Asset Manager</strong></li>\n<li>Click <strong>Add Watch Folder</strong></li>\n<li>Browse to the folder you want to monitor</li>\n<li>Configure import options</li>\n<li>Click <strong>OK</strong> to enable watching</li>\n</ol>\n\n<h3>Watch Folder Options</h3>\n<table>\n<tr><th>Option</th><th>Description</th></tr>\n<tr><td>Include Subfolders</td><td>Monitor subdirectories recursively</td></tr>\n<tr><td>File Types</td><td>Filter which file types to import</td></tr>\n<tr><td>Target Folder</td><td>Where to place imported assets in the show</td></tr>\n<tr><td>Auto-Delete Source</td><td>Remove source after successful import</td></tr>\n</table>\n\n<h3>How It Works</h3>\n<ol>\n<li>Place new media files in the watched folder</li>\n<li>Asset Watcher detects the new files</li>\n<li>Files are automatically imported into the show</li>\n<li>Optimization begins immediately</li>\n<li>Assets appear in the Assets window when ready</li>\n</ol>\n\n<h3>File Change Detection</h3>\n<p>If a source file is modified:</p>\n<ul>\n<li>The Asset Watcher detects the change</li>\n<li>The asset is marked as modified (orange icon)</li>\n<li>Re-optimization is triggered automatically</li>\n<li>Updated content is distributed to display servers</li>\n</ul>\n\n<h3>Use Cases</h3>\n<ul>\n<li><strong>Collaborative Workflows</strong> – Content creators drop files for operators</li>\n<li><strong>Live Updates</strong> – Update content during a show</li>\n<li><strong>Automated Pipelines</strong> – Integrate with render farms or CMS</li>\n</ul>",
      "Asset Transfer": "<h2>Asset Transfer</h2>\n\n<p>When going online, optimized assets must be transferred to display servers. WATCHOUT manages this automatically.</p>\n\n<h3>Transfer Process</h3>\n<ol>\n<li><strong>Comparison</strong> – Producer compares local and remote asset versions</li>\n<li><strong>Queue</strong> – Changed or new assets are queued for transfer</li>\n<li><strong>Transfer</strong> – Files are sent over the network to each server</li>\n<li><strong>Verification</strong> – Checksums confirm successful transfer</li>\n<li><strong>Ready</strong> – Server signals ready when all assets are loaded</li>\n</ol>\n\n<h3>Transfer Status</h3>\n<p>Monitor transfer progress in the Network window:</p>\n<ul>\n<li><strong>Blue progress bar</strong> – Transfer in progress</li>\n<li><strong>Percentage</strong> – Completion status per server</li>\n<li><strong>Green check</strong> – All assets transferred successfully</li>\n<li><strong>Red X</strong> – Transfer error occurred</li>\n</ul>\n\n<h3>Optimizing Transfer Speed</h3>\n<ul>\n<li><strong>Use Gigabit or faster</strong> – 1Gbps minimum, 10Gbps recommended</li>\n<li><strong>Quality switches</strong> – Avoid consumer-grade network equipment</li>\n<li><strong>Dedicated network</strong> – Separate WATCHOUT traffic from other data</li>\n<li><strong>Pre-stage assets</strong> – Copy large files manually before going online</li>\n</ul>\n\n<h3>Pre-Staging Assets</h3>\n<p>For very large shows, pre-stage assets on display servers:</p>\n<ol>\n<li>Copy optimized asset folder to display server</li>\n<li>Place in the designated asset cache location</li>\n<li>When going online, existing assets are used without transfer</li>\n</ol>\n\n<h3>Managing Disk Space</h3>\n<ul>\n<li><strong>Optimized cache</strong> – Located in the show's asset folder</li>\n<li><strong>Server cache</strong> – Stored on each display server's local drive</li>\n<li><strong>Cleanup</strong> – Remove unused optimized assets via File menu</li>\n</ul>",
      "Asset Manager Settings": "<h2>Asset Manager Settings</h2>\n\n<p>Configure the Asset Manager behavior through the Settings dialog.</p>\n\n<h3>Accessing Settings</h3>\n<p>Go to <strong>Edit → Preferences → Asset Manager</strong> or access from the Assets window menu.</p>\n\n<h3>General Settings</h3>\n<table>\n<tr><th>Setting</th><th>Description</th></tr>\n<tr><td>Cache Location</td><td>Where optimized assets are stored</td></tr>\n<tr><td>Max Cache Size</td><td>Limit on disk space for optimized files</td></tr>\n<tr><td>Auto-Optimize</td><td>Automatically optimize new imports</td></tr>\n<tr><td>Parallel Optimize</td><td>Number of simultaneous optimization jobs</td></tr>\n</table>\n\n<h3>Optimization Defaults</h3>\n<table>\n<tr><th>Setting</th><th>Description</th></tr>\n<tr><td>Target Codec</td><td>Default codec for optimized video (HAP recommended)</td></tr>\n<tr><td>Quality Level</td><td>Balance between quality and file size</td></tr>\n<tr><td>Max Resolution</td><td>Cap on output resolution</td></tr>\n<tr><td>Frame Rate</td><td>Target frame rate for optimization</td></tr>\n</table>\n\n<h3>Network Settings</h3>\n<table>\n<tr><th>Setting</th><th>Description</th></tr>\n<tr><td>Web UI Port</td><td>HTTP port for web interface (default: 3040)</td></tr>\n<tr><td>Transfer Port</td><td>Port for asset distribution</td></tr>\n<tr><td>Bandwidth Limit</td><td>Maximum network speed for transfers</td></tr>\n</table>\n\n<h3>Watch Folder Settings</h3>\n<ul>\n<li>Add, remove, and configure watched directories</li>\n<li>Set default import behavior</li>\n<li>Enable/disable watching per folder</li>\n</ul>\n\n<h3>Advanced Settings</h3>\n<ul>\n<li><strong>GPU Acceleration</strong> – Use graphics card for encoding/decoding</li>\n<li><strong>Hardware Encoder</strong> – Select specific GPU for optimization</li>\n<li><strong>Thread Count</strong> – CPU threads for software encoding</li>\n<li><strong>Memory Limit</strong> – Maximum RAM for optimization processes</li>\n</ul>\n\n<h3>Maintenance</h3>\n<ul>\n<li><strong>Clear Cache</strong> – Remove all optimized files (will re-optimize on demand)</li>\n<li><strong>Rebuild Database</strong> – Fix corruption in asset database</li>\n<li><strong>Verify Assets</strong> – Check all source files exist and are valid</li>\n<li><strong>Export Asset List</strong> – Generate report of all show assets</li>\n</ul>"
    }
  },
  "6. Timeline and Cues": {
    "overview": "<h1>TIMELINE AND CUES</h1>\n\n<p>The timeline is where your show comes to life. Learn how to arrange media, control timing, and create dynamic presentations.</p>",
    "sections": {
      "Understanding the Timeline": "<h2>Understanding the Timeline</h2>\n\n<h3>Timeline Components</h3>\n<ul>\n<li><strong>Time Ruler</strong> – Shows current position and allows navigation</li>\n<li><strong>Layers</strong> – Horizontal tracks that stack content (higher = on top)</li>\n<li><strong>Cues</strong> – Individual media items placed on layers</li>\n<li><strong>Play Head</strong> – Red line showing current playback time</li>\n</ul>\n\n<h3>Navigation</h3>\n<ul>\n<li><strong>Click</strong> in the time ruler to jump to a position</li>\n<li><strong>Scroll</strong> horizontally to move through time</li>\n<li><strong>Zoom</strong> with Numpad +/- or timeline zoom controls</li>\n</ul>",
      "Adding Media Cues": "<h2>Adding Media Cues</h2>\n\n<h3>Creating Cues</h3>\n<ol>\n<li>Drag media from the Assets window onto the Timeline</li>\n<li>Drop on an existing layer or between layers to create a new one</li>\n<li>Position the cue at the desired start time</li>\n</ol>\n\n<h3>Cue Duration</h3>\n<p>Drag the right edge of a cue to adjust its duration. For video, the duration defaults to the clip length.</p>",
      "Working with Layers": "<h2>Working with Layers</h2>\n\n<h3>Layer Stacking</h3>\n<p>Higher layers appear in front of lower layers on stage. Use this for overlaying content.</p>\n\n<h3>Layer Operations</h3>\n<ul>\n<li><strong>Insert Layer</strong> – Ctrl+I</li>\n<li><strong>Delete Layer</strong> – Ctrl+Delete</li>\n<li><strong>Reorder</strong> – Drag layer headers up/down</li>\n</ul>",
      "Adjusting Timing": "<h2>Adjusting Timing</h2>\n\n<h3>Moving Cues</h3>\n<p>Drag cues left/right to change their start time. Hold Shift to constrain to horizontal movement.</p>\n\n<h3>Trimming</h3>\n<ul>\n<li><strong>Trim Start</strong> – Drag the left edge of a cue</li>\n<li><strong>Trim End</strong> – Drag the right edge</li>\n<li><strong>Slip Edit</strong> – Hold Alt while dragging edges for video content</li>\n</ul>\n\n<h3>Snapping</h3>\n<p>Toggle snapping (Ctrl+N) to align cues to other cues or the play head.</p>",
      "Control Cues": "<h2>Control Cues</h2>\n\n<p>Control cues trigger actions rather than displaying content.</p>\n\n<h3>Types</h3>\n<ul>\n<li><strong>Play</strong> – Start playback of another timeline (Ctrl+P)</li>\n<li><strong>Pause</strong> – Pause playback (Ctrl+Shift+P)</li>\n<li><strong>Output</strong> – Send data to external devices</li>\n<li><strong>Variable</strong> – Set variable values</li>\n</ul>",
      "Comment Cues": "<h2>Comment Cues</h2>\n\n<p>Add notes and markers to your timeline.</p>\n\n<h3>Creating Comments</h3>\n<p>Use Timeline → Add Comment Cue, or right-click on the timeline.</p>\n\n<h3>Uses</h3>\n<ul>\n<li>Mark scene changes</li>\n<li>Leave notes for collaborators</li>\n<li>Create navigation markers</li>\n</ul>",
      "Output Cues": "<h2>Output Cues</h2>\n\n<p>Send control signals to external devices and systems.</p>\n\n<h3>Supported Outputs</h3>\n<ul>\n<li>Art-Net/DMX for lighting</li>\n<li>MIDI for show control</li>\n<li>TCP/UDP network commands</li>\n<li>Serial port commands</li>\n</ul>",
      "Grouping Cues": "<h2>Grouping Cues</h2>\n\n<p>Combine multiple cues into groups for easier management.</p>\n\n<h3>Creating Groups</h3>\n<ol>\n<li>Select multiple cues</li>\n<li>Go to Timeline → Group Cues</li>\n</ol>\n\n<h3>Editing Groups</h3>\n<p>Double-click a group to edit its contents. Changes affect all instances.</p>"
    }
  },
  "7. Effects and Tweens": {
    "overview": "<h1>EFFECTS AND TWEENS</h1>\n\n<p>Tweens bring your content to life with animation. Learn how to create smooth transitions and dynamic effects.</p>",
    "sections": {
      "Understanding Tweens": "<h2>Understanding Tweens</h2>\n\n<p>A tween is an animated change over time. Tweens are shown as colored bars in the timeline.</p>\n\n<h3>Tween Basics</h3>\n<ul>\n<li><strong>Keyframes</strong> – Points where values are defined</li>\n<li><strong>Interpolation</strong> – How values change between keyframes</li>\n<li><strong>Easing</strong> – Acceleration/deceleration curves</li>\n</ul>",
      "Position and Movement": "<h2>Position and Movement</h2>\n\n<p>Animate the position of content on stage.</p>\n\n<h3>Adding Position Tweens</h3>\n<ol>\n<li>Select a cue on the timeline</li>\n<li>Press <code>Alt+P</code> or use Tween → Position</li>\n<li>A position tween track appears</li>\n<li>Add keyframes by clicking on the track</li>\n</ol>",
      "Scale and Size": "<h2>Scale and Size</h2>\n\n<p>Animate the size of content.</p>\n\n<h3>Scale Tween</h3>\n<p>Press <code>Alt+S</code> to add a scale tween. Animate from 0% to 100% for a grow effect.</p>",
      "Rotation Effects": "<h2>Rotation Effects</h2>\n\n<p>Rotate content around different axes.</p>\n\n<h3>Rotation Types</h3>\n<ul>\n<li><strong>Z Rotation</strong> (Alt+R) – Standard 2D rotation</li>\n<li><strong>Y Rotation</strong> (Alt+Y) – Flip horizontally in 3D</li>\n<li><strong>X Rotation</strong> – Flip vertically in 3D</li>\n</ul>",
      "Opacity and Fades": "<h2>Opacity and Fades</h2>\n\n<p>Control transparency for fade effects.</p>\n\n<h3>Fade In/Out</h3>\n<ul>\n<li><strong>Fade In</strong> – Select cue, use Tween → Fade In</li>\n<li><strong>Fade Out</strong> – Select cue, use Tween → Fade Out</li>\n<li><strong>Cross Fade</strong> – Blend between overlapping cues</li>\n</ul>\n\n<h3>Manual Opacity</h3>\n<p>Press <code>Alt+O</code> to add an opacity tween for custom fade curves.</p>",
      "Cropping": "<h2>Cropping</h2>\n\n<p>Animate the visible area of content.</p>\n\n<h3>Crop Controls</h3>\n<ul>\n<li>Crop All – <code>Alt+C</code></li>\n<li>Crop individual sides for reveal effects</li>\n</ul>",
      "Color Adjustments": "<h2>Color Adjustments</h2>\n\n<p>Animate color properties for dynamic effects.</p>\n\n<h3>Available Adjustments</h3>\n<ul>\n<li><strong>Brightness</strong> – Overall luminance</li>\n<li><strong>Contrast</strong> – Dynamic range</li>\n<li><strong>Saturation</strong> – Color intensity</li>\n<li><strong>Hue</strong> – Color shift</li>\n<li><strong>RGB Offset/Gain</strong> – Channel-specific adjustments</li>\n</ul>",
      "Blur Effects": "<h2>Blur Effects</h2>\n\n<p>Add blur for depth of field or transition effects.</p>\n\n<h3>Adding Blur</h3>\n<p>Use <code>Alt+B</code> or Tween → Blur to add blur animation.</p>",
      "Audio Volume": "<h2>Audio Volume</h2>\n\n<p>Animate audio levels over time.</p>\n\n<h3>Volume Tween</h3>\n<p>Press <code>Alt+V</code> to add volume automation. Create fades and ducking effects.</p>"
    }
  },
  "8. Playback": {
    "overview": "<h1>PLAYBACK</h1>\n\n<p>Learn how to preview your show, connect to display servers, and run your presentation live.</p>",
    "sections": {
      "Starting and Stopping": "<h2>Starting and Stopping</h2>\n\n<h3>Playback Controls</h3>\n<ul>\n<li><strong>Spacebar</strong> – Toggle play/pause</li>\n<li><strong>Numpad 0</strong> – Start playback</li>\n<li><strong>Escape</strong> – Pause</li>\n<li><strong>Numpad *</strong> – Jump to last start position</li>\n</ul>\n\n<h3>Timeline Navigation</h3>\n<p>Click anywhere in the time ruler to jump to that position. Use keyboard shortcuts for precise navigation.</p>",
      "Preview Mode": "<h2>Preview Mode</h2>\n\n<p>Preview your show directly in the Stage window without going online to display servers.</p>\n\n<h3>Preview Quality</h3>\n<p>Adjust preview quality in the Stage menu:</p>\n<ul>\n<li><strong>Best Quality</strong> – Full resolution (slower)</li>\n<li><strong>Thumbnails</strong> – Faster preview using lower resolution</li>\n<li><strong>Wireframes</strong> – Outlines only for maximum performance</li>\n</ul>",
      "Connecting to Display Servers": "<h2>Connecting to Display Servers</h2>\n\n<h3>Automatic Discovery</h3>\n<p>WATCHOUT automatically discovers display servers on the same network. They appear in the Network window.</p>\n\n<h3>Manual Connection</h3>\n<p>If a server doesn't appear, verify:</p>\n<ol>\n<li>Both computers are on the same network subnet</li>\n<li>Firewall rules are properly configured</li>\n<li>The display server software is running</li>\n</ol>",
      "Going Online": "<h2>Going Online</h2>\n\n<p>Going online sends your show data to display servers for synchronized playback.</p>\n\n<h3>Steps</h3>\n<ol>\n<li>Ensure display servers are connected (green in Network window)</li>\n<li>Click the <strong>Online</strong> button or press <code>Ctrl+L</code></li>\n<li>Wait for assets to transfer to servers</li>\n<li>Status turns green when ready</li>\n</ol>",
      "Running Your Show": "<h2>Running Your Show</h2>\n\n<h3>Live Playback</h3>\n<ol>\n<li>Go online with all display servers</li>\n<li>Press Spacebar to start playback</li>\n<li>All connected servers play in sync</li>\n</ol>\n\n<h3>Show Control</h3>\n<p>During live playback, you can:</p>\n<ul>\n<li>Jump to any point in the timeline</li>\n<li>Pause and resume</li>\n<li>Make live adjustments to content</li>\n</ul>"
    }
  },
  "9. Network Setup": {
    "overview": "<h1>NETWORK SETUP</h1>\n\n<p>Configure your network for optimal WATCHOUT performance. Proper network setup is essential for synchronized multi-display playback.</p>",
    "sections": {
      "Network Overview": "<h2>Network Overview</h2>\n\n<h3>Network Architecture</h3>\n<p>WATCHOUT uses a star topology with the Producer computer acting as the director, controlling multiple display servers.</p>\n\n<h3>Requirements</h3>\n<ul>\n<li>Gigabit Ethernet minimum</li>\n<li>All devices on the same subnet</li>\n<li>Low-latency switches recommended</li>\n<li>Dedicated VLAN for WATCHOUT traffic (recommended)</li>\n</ul>",
      "Display Servers": "<h2>Display Servers</h2>\n\n<p>Display servers are computers that render and output video to projectors or screens.</p>\n\n<h3>Server Setup</h3>\n<ol>\n<li>Install WATCHOUT on the display computer</li>\n<li>Run the Display Server application</li>\n<li>Configure GPU outputs in Windows Display Settings</li>\n<li>Assign displays to outputs in WATCHOUT</li>\n</ol>",
      "Connecting Devices": "<h2>Connecting Devices</h2>\n\n<h3>Automatic Discovery</h3>\n<p>WATCHOUT uses multicast discovery. All devices on the same subnet automatically find each other.</p>\n\n<h3>Troubleshooting Connection</h3>\n<ul>\n<li>Verify all devices have valid IP addresses in the same subnet</li>\n<li>Check that multicast traffic is not blocked</li>\n<li>Disable any WiFi connections on WATCHOUT computers</li>\n</ul>",
      "Firewall Configuration": "<h2>Firewall Configuration</h2>\n\n<h3>Required Ports</h3>\n<table>\n<tr><th>Port</th><th>Protocol</th><th>Purpose</th></tr>\n<tr><td>3039</td><td>TCP</td><td>Primary communication</td></tr>\n<tr><td>3040</td><td>TCP</td><td>Asset transfer</td></tr>\n<tr><td>40400-40500</td><td>UDP</td><td>Discovery and sync</td></tr>\n</table>\n\n<h3>Windows Firewall</h3>\n<p>WATCHOUT installer creates firewall rules automatically. For manual configuration, allow both inbound and outbound traffic on the ports above.</p>",
      "NDI Video Sources": "<h2>NDI Video Sources</h2>\n\n<p>Network Device Interface (NDI) allows video transmission over standard networks.</p>\n\n<h3>Using NDI</h3>\n<ol>\n<li>Add an NDI source in the Assets window</li>\n<li>Select the NDI stream from available sources</li>\n<li>Use like any other media in your timeline</li>\n</ol>",
      "Dante Audio": "<h2>Dante Audio</h2>\n\n<p>Dante provides professional-quality networked audio.</p>\n\n<h3>Configuration</h3>\n<p>Configure Dante routing using Audinate's Dante Controller. WATCHOUT appears as a Dante-enabled device on the network.</p>"
    }
  },
  "10. Keyboard Shortcuts": {
    "overview": "<h1>KEYBOARD SHORTCUTS</h1>\n\n<p>Master these keyboard shortcuts to speed up your workflow.</p>",
    "sections": {
      "File Operations": "<h2>File Operations</h2>\n\n<table>\n<tr><th>Shortcut</th><th>Action</th></tr>\n<tr><td><code>Ctrl+N</code></td><td>New show</td></tr>\n<tr><td><code>Ctrl+O</code></td><td>Open show</td></tr>\n<tr><td><code>Ctrl+S</code></td><td>Save show</td></tr>\n<tr><td><code>Ctrl+Q</code></td><td>Quit application</td></tr>\n</table>",
      "Edit Commands": "<h2>Edit Commands</h2>\n\n<table>\n<tr><th>Shortcut</th><th>Action</th></tr>\n<tr><td><code>Ctrl+Z</code></td><td>Undo</td></tr>\n<tr><td><code>Ctrl+Shift+Z</code></td><td>Redo</td></tr>\n<tr><td><code>Ctrl+X</code></td><td>Cut</td></tr>\n<tr><td><code>Ctrl+C</code></td><td>Copy</td></tr>\n<tr><td><code>Ctrl+V</code></td><td>Paste</td></tr>\n<tr><td><code>Delete</code></td><td>Delete selected</td></tr>\n<tr><td><code>Ctrl+A</code></td><td>Select all</td></tr>\n<tr><td><code>Enter</code></td><td>Open properties</td></tr>\n</table>",
      "Stage Navigation": "<h2>Stage Navigation</h2>\n\n<table>\n<tr><th>Shortcut</th><th>Action</th></tr>\n<tr><td><code>Ctrl+Shift+D</code></td><td>Frame all displays</td></tr>\n<tr><td><code>Ctrl+Shift+O</code></td><td>Scroll to origin</td></tr>\n<tr><td><code>Ctrl+1</code> to <code>5</code></td><td>Set zoom level</td></tr>\n<tr><td><code>Ctrl+Alt+Drag</code></td><td>Pan view</td></tr>\n<tr><td><code>Ctrl+Wheel</code></td><td>Zoom in/out</td></tr>\n<tr><td><code>Ctrl+Arrow</code></td><td>Nudge selection 1px</td></tr>\n<tr><td><code>Ctrl+Shift+Arrow</code></td><td>Nudge selection 10px</td></tr>\n</table>",
      "Timeline Controls": "<h2>Timeline Controls</h2>\n\n<table>\n<tr><th>Shortcut</th><th>Action</th></tr>\n<tr><td><code>Spacebar</code></td><td>Play/Pause toggle</td></tr>\n<tr><td><code>Numpad 0</code></td><td>Start playback</td></tr>\n<tr><td><code>Escape</code></td><td>Pause</td></tr>\n<tr><td><code>Numpad *</code></td><td>Jump to last start</td></tr>\n<tr><td><code>Numpad +</code></td><td>Zoom in timeline</td></tr>\n<tr><td><code>Numpad -</code></td><td>Zoom out timeline</td></tr>\n<tr><td><code>Ctrl+I</code></td><td>Insert layer</td></tr>\n<tr><td><code>Ctrl+Delete</code></td><td>Delete layer</td></tr>\n<tr><td><code>Ctrl+P</code></td><td>Add play cue</td></tr>\n<tr><td><code>Ctrl+Shift+P</code></td><td>Add pause cue</td></tr>\n</table>",
      "Tween Shortcuts": "<h2>Tween Shortcuts</h2>\n\n<table>\n<tr><th>Shortcut</th><th>Tween Type</th></tr>\n<tr><td><code>Alt+P</code></td><td>Position</td></tr>\n<tr><td><code>Alt+S</code></td><td>Scale</td></tr>\n<tr><td><code>Alt+O</code></td><td>Opacity</td></tr>\n<tr><td><code>Alt+R</code></td><td>Rotation (Z-axis)</td></tr>\n<tr><td><code>Alt+Y</code></td><td>Rotation (Y-axis)</td></tr>\n<tr><td><code>Alt+C</code></td><td>Crop</td></tr>\n<tr><td><code>Alt+B</code></td><td>Blur</td></tr>\n<tr><td><code>Alt+V</code></td><td>Volume</td></tr>\n<tr><td><code>Alt+H</code></td><td>Hue</td></tr>\n</table>",
      "Window Management": "<h2>Window Management</h2>\n\n<table>\n<tr><th>Shortcut</th><th>Action</th></tr>\n<tr><td><code>Ctrl+Tab</code></td><td>Cycle through windows</td></tr>\n<tr><td><code>Ctrl+L</code></td><td>Toggle online</td></tr>\n<tr><td><code>Ctrl+N</code></td><td>Toggle snapping</td></tr>\n<tr><td><code>Ctrl+Shift+1-9</code></td><td>Save/Load layout preset</td></tr>\n</table>"
    }
  },
  "11. Troubleshooting": {
    "overview": "<h1>TROUBLESHOOTING</h1>\n\n<p>Solutions to common issues and tips for optimal performance.</p>",
    "sections": {
      "Common Issues": "<h2>Common Issues</h2>\n\n<h3>Application Won't Start</h3>\n<ul>\n<li>Run as Administrator</li>\n<li>Check for Windows updates</li>\n<li>Verify graphics drivers are up to date</li>\n<li>Check license status</li>\n</ul>\n\n<h3>Media Won't Import</h3>\n<ul>\n<li>Verify the file format is supported</li>\n<li>Check file isn't corrupted</li>\n<li>Ensure you have read permissions</li>\n</ul>",
      "Performance Tips": "<h2>Performance Tips</h2>\n\n<h3>Optimize Your System</h3>\n<ul>\n<li>Use SSD storage for media files</li>\n<li>Close unnecessary background applications</li>\n<li>Disable Windows animations and effects</li>\n<li>Set power plan to High Performance</li>\n</ul>\n\n<h3>Media Optimization</h3>\n<ul>\n<li>Use HAP codec for best video performance</li>\n<li>Match media resolution to display resolution</li>\n<li>Avoid excessive overlapping content</li>\n</ul>",
      "Display Problems": "<h2>Display Problems</h2>\n\n<h3>No Output on Display</h3>\n<ol>\n<li>Verify display server is online (green status)</li>\n<li>Check display is assigned to correct output</li>\n<li>Verify GPU output is active in Windows</li>\n<li>Check cables and connections</li>\n</ol>\n\n<h3>Stuttering Playback</h3>\n<ul>\n<li>Use HAP codec instead of H.264/HEVC</li>\n<li>Reduce video resolution if needed</li>\n<li>Check disk read speed</li>\n<li>Reduce number of simultaneous videos</li>\n</ul>",
      "Network Issues": "<h2>Network Issues</h2>\n\n<h3>Display Servers Not Found</h3>\n<ol>\n<li>Verify both computers are on the same subnet</li>\n<li>Check firewall settings</li>\n<li>Disable WiFi on WATCHOUT computers</li>\n<li>Try pinging between computers</li>\n</ol>\n\n<h3>Slow Asset Transfer</h3>\n<ul>\n<li>Use Gigabit or faster network</li>\n<li>Check for network congestion</li>\n<li>Consider pre-staging assets on display servers</li>\n</ul>",
      "Media Playback Issues": "<h2>Media Playback Issues</h2>\n\n<h3>Video Doesn't Play</h3>\n<ul>\n<li>Wait for optimization to complete (green icon)</li>\n<li>Try re-optimizing the asset</li>\n<li>Check source file isn't corrupted</li>\n<li>Try converting to HAP format</li>\n</ul>\n\n<h3>Audio Issues</h3>\n<ul>\n<li>Verify audio device is configured correctly</li>\n<li>Check volume levels aren't muted</li>\n<li>Ensure audio file format is supported</li>\n</ul>",
      "Getting Help": "<h2>Getting Help</h2>\n\n<h3>Support Resources</h3>\n<ul>\n<li><strong>Documentation</strong> – dataton.com/watchout-7-users-guide</li>\n<li><strong>Support</strong> – Contact Dataton technical support</li>\n<li><strong>Training</strong> – Official WATCHOUT training courses</li>\n</ul>\n\n<h3>Create Feedback Report</h3>\n<p>Use <strong>Help → Create Feedback Report</strong> to generate a diagnostic package for support.</p>\n\n<h3>Log Files</h3>\n<p>Access log files via <strong>Help → Explore Logs</strong> for detailed troubleshooting information.</p>"
    }
  }
};
