// WATCHOUT 7 User Guide - Table of Contents Data
// Auto-generated by build-content.js - DO NOT EDIT DIRECTLY
// Edit the markdown files in /content instead

// SVG Icons (Lucide-style)
const icons = {
    book: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>`,
    settings: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>`,
    layout: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>`,
    monitor: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line></svg>`,
    film: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg>`,
    clock: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>`,
    play: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>`,
    sliders: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>`,
    globe: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>`,
    keyboard: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2" ry="2"></rect><path d="M6 8h.001"></path><path d="M10 8h.001"></path><path d="M14 8h.001"></path><path d="M18 8h.001"></path><path d="M8 12h.001"></path><path d="M12 12h.001"></path><path d="M16 12h.001"></path><path d="M7 16h10"></path></svg>`,
    alertCircle: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>`,
    fileText: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>`,
    link: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>`
};

// Get icon SVG by name
function getIcon(iconName) {
    return icons[iconName] || icons.fileText;
}

const tocData = [
    {
        "level": 1,
        "title": "1. Getting Started",
        "page": 1,
        "icon": "book"
    },
    {
        "level": 2,
        "title": "Welcome to WATCHOUT 7",
        "page": 1,
        "description": "WATCHOUT 7 is the latest evolution of Dataton's award-winning multi-display production and playback system. Designed ..."
    },
    {
        "level": 2,
        "title": "System Requirements",
        "page": 2,
        "description": "WATCHOUT 7 requires a Windows-based computer with modern hardware to deliver optimal performance. The requirements di..."
    },
    {
        "level": 2,
        "title": "Installing WATCHOUT",
        "page": 3,
        "description": "Setting up WATCHOUT represents the first step toward creating your show. The installation process is straightforward,..."
    },
    {
        "level": 2,
        "title": "Launching the Application",
        "page": 4,
        "description": "Once WATCHOUT is installed, you are ready to launch the software. How you launch it depends on whether you are workin..."
    },
    {
        "level": 2,
        "title": "Network Configuration",
        "page": 5,
        "description": "Establishing a robust and properly configured network is critical for WATCHOUT 7. The system relies on the network no..."
    },
    {
        "level": 2,
        "title": "Quick Start Tutorial",
        "page": 6,
        "description": "Follow these steps to create your first simple presentation in WATCHOUT 7."
    },
    {
        "level": 1,
        "title": "2. The Interface",
        "page": 1,
        "icon": "layout"
    },
    {
        "level": 2,
        "title": "Main Window Overview",
        "page": 1,
        "description": "The WATCHOUT 7 Producer interface presents a modern, flexible workspace designed for efficient show creation and mana..."
    },
    {
        "level": 2,
        "title": "The Stage Window",
        "page": 2,
        "description": "The Stage is your visual canvas—a representation of all your displays and how content appears on them. It provides a ..."
    },
    {
        "level": 2,
        "title": "The Timeline Window",
        "page": 3,
        "description": "The Timeline is where you orchestrate your show—arranging media and controlling precisely when things happen. It prov..."
    },
    {
        "level": 2,
        "title": "The Assets Window",
        "page": 4,
        "description": "The Assets window is your media library—the central repository for all images, videos, audio files, and other resourc..."
    },
    {
        "level": 2,
        "title": "The Properties Panel",
        "page": 5,
        "description": "The Properties panel is a context-sensitive inspector that displays settings for whatever is currently selected—displ..."
    },
    {
        "level": 2,
        "title": "The Network Window",
        "page": 6,
        "description": "The Network window shows all WATCHOUT devices on your network and their status. It provides centralized management of..."
    },
    {
        "level": 2,
        "title": "Customizing Your Workspace",
        "page": 7,
        "description": "WATCHOUT 7's interface is fully customizable to match your workflow. The flexible window system allows you to arrange..."
    },
    {
        "level": 2,
        "title": "The Nodes Window",
        "page": 8,
        "description": "---\r\ntitle: \"The Nodes Window\"\r\n---"
    },
    {
        "level": 1,
        "title": "3. Working with Shows",
        "page": 1,
        "icon": "fileText"
    },
    {
        "level": 2,
        "title": "Creating a New Show",
        "page": 1,
        "description": "Creating a new show sets up the timeline, stage, and routing model for your project. In WATCHOUT 7, a show can be loc..."
    },
    {
        "level": 2,
        "title": "Opening Existing Shows",
        "page": 2,
        "description": "WATCHOUT supports opening shows from disk and attaching to shows currently managed by a Director."
    },
    {
        "level": 2,
        "title": "Saving Your Work",
        "page": 3,
        "description": "Saving in WATCHOUT covers both project state and operational safety. Use frequent saves, especially before network ac..."
    },
    {
        "level": 2,
        "title": "Show Properties",
        "page": 4,
        "description": "Show Properties define global behavior for your project. Configure them early, then revisit before technical rehearsals."
    },
    {
        "level": 1,
        "title": "4. Displays and Outputs",
        "page": 1,
        "icon": "monitor"
    },
    {
        "level": 2,
        "title": "Adding Displays",
        "page": 1,
        "description": "Displays are the output surfaces your cues render to. In WATCHOUT 7, each display is a configurable device object wit..."
    },
    {
        "level": 2,
        "title": "Virtual Displays",
        "page": 2,
        "description": "A virtual display behaves like a normal display in the Stage and Timeline, but it is not tied to a physical connector..."
    },
    {
        "level": 2,
        "title": "3D Mapping Projectors",
        "page": 3,
        "description": "Projector displays extend WATCHOUT from flat 2D layouts to spatially mapped output. Projector mode uses camera/frustu..."
    },
    {
        "level": 2,
        "title": "Display Grid Setup",
        "page": 4,
        "description": "Grid tools speed up setup for LED walls, tiled monitors, and repeated projection arrays."
    },
    {
        "level": 2,
        "title": "Display Properties",
        "page": 5,
        "description": "Display Properties control how each display is rendered, routed, and calibrated."
    },
    {
        "level": 2,
        "title": "Edge Blending",
        "page": 6,
        "description": "Edge blending smooths overlap regions between adjacent projected outputs so they appear as one continuous image."
    },
    {
        "level": 2,
        "title": "Geometry Correction",
        "page": 7,
        "description": "Geometry correction aligns rendered imagery to real-world surfaces. In WATCHOUT, this is handled through warp geometr..."
    },
    {
        "level": 1,
        "title": "5. Assets & Asset Manager",
        "page": 1,
        "icon": "film"
    },
    {
        "level": 2,
        "title": "Asset Manager",
        "page": 1,
        "description": "The Asset Manager is a core component of WATCHOUT 7 that manages all media files used in your shows."
    },
    {
        "level": 2,
        "title": "Asset Types",
        "page": 2,
        "description": "WATCHOUT 7 supports a wide variety of media types, each with specific capabilities and use cases."
    },
    {
        "level": 2,
        "title": "Asset Properties",
        "page": 3,
        "description": "Each asset has properties that control how it behaves in your show. Access properties by selecting an asset and viewi..."
    },
    {
        "level": 2,
        "title": "Formats & Codecs",
        "page": 4,
        "description": "Choosing the right format and codec is crucial for optimal playback performance."
    },
    {
        "level": 2,
        "title": "Web User Interface",
        "page": 5,
        "description": "WATCHOUT 7 includes a web-based interface for managing assets remotely. This allows team members to upload and organi..."
    },
    {
        "level": 2,
        "title": "Asset Watcher",
        "page": 6,
        "description": "The Asset Watcher automatically monitors designated folders for new or changed files, streamlining the content workflow."
    },
    {
        "level": 2,
        "title": "Asset Transfer",
        "page": 7,
        "description": "When going online, optimized assets must be transferred to display servers. WATCHOUT manages this automatically."
    },
    {
        "level": 2,
        "title": "Asset Manager Settings",
        "page": 8,
        "description": "Configure the Asset Manager behavior through the Settings dialog."
    },
    {
        "level": 2,
        "title": "Import, Export, and Mapping",
        "page": 9,
        "description": "Beyond normal drag-and-drop ingest, the Assets window includes transfer workflows for moving asset sets between syste..."
    },
    {
        "level": 1,
        "title": "6. Timeline and Cues",
        "page": 1,
        "icon": "clock"
    },
    {
        "level": 2,
        "title": "Understanding the Timeline",
        "page": 1,
        "description": "The Timeline is where show logic is sequenced. Cues on layers define what plays, when it plays, and how it behaves."
    },
    {
        "level": 2,
        "title": "Adding Media Cues",
        "page": 2,
        "description": "Media cues are created by placing assets on a timeline."
    },
    {
        "level": 2,
        "title": "Working with Layers",
        "page": 3,
        "description": "Layers determine draw order and help organize complex timelines."
    },
    {
        "level": 2,
        "title": "Adjusting Timing",
        "page": 4,
        "description": "Precise timing is central to show quality. WATCHOUT provides direct manipulation and command-based timing edits."
    },
    {
        "level": 2,
        "title": "Control Cues",
        "page": 5,
        "description": "Control cues affect playback state instead of rendering media."
    },
    {
        "level": 2,
        "title": "Comment Cues",
        "page": 6,
        "description": "Comment cues (marker cues) provide timeline annotations for operators, programmers, and show callers."
    },
    {
        "level": 2,
        "title": "Output Cues",
        "page": 7,
        "description": "Output cues transmit external control data during timeline playback."
    },
    {
        "level": 2,
        "title": "Grouping Cues",
        "page": 8,
        "description": "Grouping lets you treat multiple cues as a single composition unit."
    },
    {
        "level": 2,
        "title": "Variables and Variable Cues",
        "page": 9,
        "description": "WATCHOUT variables let you drive timeline behavior and runtime values with explicit numeric controls."
    },
    {
        "level": 2,
        "title": "Timeline Triggers and Expressions",
        "page": 10,
        "description": "Timelines can react automatically to expression-based trigger rules for play, pause, and stop."
    },
    {
        "level": 2,
        "title": "ArtNet Fixture Cues",
        "page": 11,
        "description": "WATCHOUT includes an ArtNet fixture workflow spanning Assets and Cue Properties."
    },
    {
        "level": 1,
        "title": "7. Effects and Tweens",
        "page": 1,
        "icon": "sliders"
    },
    {
        "level": 2,
        "title": "Understanding Tweens",
        "page": 1,
        "description": "Tweens are time-based value changes attached to cues. They define animation curves for motion, opacity, color, crop, ..."
    },
    {
        "level": 2,
        "title": "Position and Movement",
        "page": 2,
        "description": "Position tweens animate where a cue appears on Stage over time."
    },
    {
        "level": 2,
        "title": "Scale and Size",
        "page": 3,
        "description": "Scale controls cue size over time and can be driven by tween points or static cue settings."
    },
    {
        "level": 2,
        "title": "Rotation Effects",
        "page": 4,
        "description": "Rotation tweens control orientation in 2D and 3D contexts."
    },
    {
        "level": 2,
        "title": "Opacity and Fades",
        "page": 5,
        "description": "Opacity and fade controls define visibility transitions for cues."
    },
    {
        "level": 2,
        "title": "Cropping",
        "page": 6,
        "description": "Crop tweens animate the visible bounds of a cue and are useful for reveals, wipes, and framing."
    },
    {
        "level": 2,
        "title": "Color Adjustments",
        "page": 7,
        "description": "Color tweens let you animate tonal and channel-level color properties directly on cues."
    },
    {
        "level": 2,
        "title": "Blur Effects",
        "page": 8,
        "description": "WATCHOUT provides a Gaussian Blur tween for softening and defocusing content over time."
    },
    {
        "level": 2,
        "title": "Audio Volume",
        "page": 9,
        "description": "Volume tweens automate cue loudness over time."
    },
    {
        "level": 1,
        "title": "8. Playback",
        "page": 1,
        "icon": "play"
    },
    {
        "level": 2,
        "title": "Starting and Stopping",
        "page": 1,
        "description": "Playback is controlled per timeline (or composition timeline) using run, pause, and stop states."
    },
    {
        "level": 2,
        "title": "Preview Mode",
        "page": 2,
        "description": "Preview mode lets you validate timing, transitions, and composition flow directly in Producer before committing to fu..."
    },
    {
        "level": 2,
        "title": "Connecting to Display Servers",
        "page": 3,
        "description": "In WATCHOUT 7, display servers are discovered nodes running Runner/renderer services. Producer uses discovered node m..."
    },
    {
        "level": 2,
        "title": "Going Online",
        "page": 4,
        "description": "Operationally, going online means your show is actively controlled through a Director with reachable Runner and Asset..."
    },
    {
        "level": 2,
        "title": "Running Your Show",
        "page": 5,
        "description": "Running a show reliably is mostly about repeatable procedure. Build a fixed preflight and execution rhythm."
    },
    {
        "level": 1,
        "title": "9. Network Setup",
        "page": 1,
        "icon": "globe"
    },
    {
        "level": 2,
        "title": "Network Overview",
        "page": 1,
        "description": "WATCHOUT 7 is a distributed system where Producer coordinates Director, Runner, and Asset Manager services across the..."
    },
    {
        "level": 2,
        "title": "Display Servers",
        "page": 2,
        "description": "A display server node is typically a Runner system responsible for rendering and output."
    },
    {
        "level": 2,
        "title": "Connecting Devices",
        "page": 3,
        "description": "In WATCHOUT, devices (displays, audio devices, capture sources) are bound to discovered node aliases."
    },
    {
        "level": 2,
        "title": "Firewall Configuration",
        "page": 4,
        "description": "WATCHOUT installer scripts create inbound firewall rules for required network behavior and executables."
    },
    {
        "level": 2,
        "title": "NDI Video Sources",
        "page": 5,
        "description": "WATCHOUT 7 supports NDI for both ingest and output workflows."
    },
    {
        "level": 2,
        "title": "Dante Audio",
        "page": 6,
        "description": "WATCHOUT supports Dante as an audio device type for networked professional audio routing."
    },
    {
        "level": 2,
        "title": "Node Management and Maintenance",
        "page": 7,
        "description": "Node maintenance actions are available in host/device properties under Network Actions."
    },
    {
        "level": 1,
        "title": "10. Keyboard Shortcuts",
        "page": 1,
        "icon": "keyboard"
    },
    {
        "level": 2,
        "title": "File Operations",
        "page": 1,
        "description": "These are the primary default shortcuts for show-file work."
    },
    {
        "level": 2,
        "title": "Edit Commands",
        "page": 2,
        "description": "These shortcuts are context-sensitive and operate on the active edit target."
    },
    {
        "level": 2,
        "title": "Stage Navigation",
        "page": 3,
        "description": "Use these shortcuts to frame, scale, and nudge content quickly in Stage workflows."
    },
    {
        "level": 2,
        "title": "Timeline Controls",
        "page": 4,
        "description": "These shortcuts are central to timeline operation and cue management."
    },
    {
        "level": 2,
        "title": "Tween Shortcuts",
        "page": 5,
        "description": "Tween shortcuts toggle common animation/effect tracks on selected cues."
    },
    {
        "level": 2,
        "title": "Window Management",
        "page": 6,
        "description": "These shortcuts help you move quickly between WATCHOUT windows and layout presets."
    },
    {
        "level": 1,
        "title": "11. Troubleshooting",
        "page": 1,
        "icon": "alertCircle"
    },
    {
        "level": 2,
        "title": "Common Issues",
        "page": 1,
        "description": "This section covers high-frequency problems seen during setup and rehearsal."
    },
    {
        "level": 2,
        "title": "Performance Tips",
        "page": 2,
        "description": "Performance issues are usually a combination of media complexity, output load, and node configuration."
    },
    {
        "level": 2,
        "title": "Display Problems",
        "page": 3,
        "description": "When a display misbehaves, diagnose in this order: routing, output mode, geometry, then content."
    },
    {
        "level": 2,
        "title": "Network Issues",
        "page": 4,
        "description": "Most network failures fall into discovery, firewall, or host-alias consistency problems."
    },
    {
        "level": 2,
        "title": "Media Playback Issues",
        "page": 5,
        "description": "Playback errors usually come from media format compatibility, missing data, or timing/resource pressure."
    },
    {
        "level": 2,
        "title": "Getting Help",
        "page": 6,
        "description": "When escalation is needed, gather diagnostics first so support can reproduce and resolve quickly."
    }
];

// Process TOC data into hierarchical structure
function processHierarchy() {
    const chapters = [];
    let currentChapter = null;

    tocData.forEach((item) => {
        if (item.level === 1) {
            const isDisabled = typeof wikiConfig !== 'undefined' && 
                wikiConfig.disabledChapters && 
                wikiConfig.disabledChapters.includes(item.title);

            currentChapter = {
                ...item,
                disabled: isDisabled,
                subsections: []
            };
            chapters.push(currentChapter);
        } else if (item.level === 2 && currentChapter) {
            currentChapter.subsections.push(item);
        }
    });

    return chapters;
}

const chaptersData = processHierarchy();
